import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useRouter } from "next/router"

import styles from "../styles/Home.module.css"

const Home: NextPage = ({ product }:any) => {
  const router = useRouter()
  const productIds = [1, 2, 3]

  return (
    <div className={styles.container}>
      <Head>
        <title>NUMBLE:: 쿠팡 클론</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:image" content="//image10.coupangcdn.com/image/mobile/v3/img_fb_like.png" />
        <meta property="og:title" content="NUMBLE:: 쿠팡 클론" />
        <meta property="og:url" content="https://www.coupang.com" />
        <meta property="og:description" content="COUPANG" />
        <meta property="og:type" content="website" />
        <link rel="shortcut icon" href="//image9.coupangcdn.com/image/coupang/favicon/v2/favicon.ico" type="image/x-icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello World!</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/products/[productId].tsx</code>,
          <code className={styles.code}>src/components</code>
        </p>

        {
          productIds.map((productId) => (
            <Link key={productId} href="/products/[productId]" as={`/products/${productId}`}>
              <a>상품상세페이지 {productId}</a>
            </Link>
          ))
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/numble.png" alt="NUMBLE Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
